### ISSUE TITLE
Drop6

### ISSUE THREAD

**Issue by Sephirox** [NekoNova/Generalist#2]
Generalist Error. Can't Load

**Comment by coding-red-panda** [comment]
can you copy it?
Probably API related.

**Comment by Sephirox** [comment]
...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:818: attempt to call field 'GetPlacedDecorList' (a nil value)
stack trace:
    ...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:818: in function 'GetCharDecor'
    ...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:495: in function 'UpdateCurrentCharacter'
    ...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:271: in function <...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:258>

...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:818: attempt to call field 'GetPlacedDecorList' (a nil value)
stack trace:
    ...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:818: in function 'GetCharDecor'
    ...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:495: in function 'UpdateCurrentCharacter'
    ...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:271: in function <...ing\NCSOFT\WildStar\Addons\generalist\Generalist.lua:258>

**Comment by coding-red-panda** [comment]
yeah thought as much.
They moved the Housing stuff around a bit. Should not be too hard to fix.

**Comment by coding-red-panda** [comment]
Fixed in version 2.0
